apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
        - name: survey-app
          image: us-central1-docker.pkg.dev/project-8a788ef4-4bf5-45aa-996/survey-repo/survey-app:latest
          ports:
            - containerPort: 5000